## 4장 넘파이 기본 : 배열과 벡터 연산

In [6]:
# 넘파이의 속도
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

649 µs ± 7.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
%timeit my_arr2 = my_arr*2

%timeit my_list2 = my_list*2

704 µs ± 33.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.44 ms ± 41.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


---

### 다차원 배열 객체 ndarray
넘파이의 핵심 기능은 ndarray라고 하는 N차원의 배열 객체다.
ndarray는 파이썬에서 사용할 수 있는 대규모 데이터셋을 땀을 수 있는 빠르고 유연한 자료구조다.
배열을 사용하면 스칼라 원소 간의 연산에 사용하는 문법과 비슷한 방식을 사용해 전체 데이터 블록에 수학적 연산을 수행할 수 있다.

In [9]:
import numpy as np
data = np.array([[1.5, 3, -1], [0, -3, 6.5]])
print(data)

[[ 1.5  3.  -1. ]
 [ 0.  -3.   6.5]]


In [10]:
data*10

array([[ 15.,  30., -10.],
       [  0., -30.,  65.]])

In [11]:
data+data

array([[ 3.,  6., -2.],
       [ 0., -6., 13.]])

ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.
즉, ndarray의 모든 원소는 같은 자료형이어야 한다.
모든 배열은 각 차원의 크기를 알려주는 ```shape``` 튜플과 배열에 저장된 자료형을 알려주는 ```dtype``` 객체를 갖는다.
또한, ```ndim```으로 배열의 차원을 확인할 수 있다.
* 차원 : 열의 개수

In [27]:
print(f"data의 배열은", data.shape, f"입니다.")
print(f"data의 배열에 저장된 자료형은", data.dtype, f"입니다.")
print(f"data의 차원은 ", data.ndim, f"입니다.")

data의 배열은 (2, 3) 입니다.
data의 배열에 저장된 자료형은 float64 입니다.
data의 차원은  2 입니다.


#### ndarray 생성하기
* 배열을 생성하는 가장 쉬운 방법은 array 함수를 이용하는 것이다.
* 순차적인 객체(배열도 포함한)를 받아서 넘겨받은 데이터가 들어 있는 새로운 넘파이 배열을 생성한다.
* 다음과 같이 파이썬 리스트는 변환하기 좋은 예다.
    * 리스트 길이가 동일한 중첩된 순차 데이터는 다차원 배열로 변환된다.

In [28]:
import numpy as np

data1 = [[6, 1], [-5.2, 3], [7, 0]] # 3 X 2 행렬
data2 = [6, 1, -5.2, 3, 7, 0] # 6 X 1 행렬

arr1 = np.array(data1)
arr2 = np.array(data2)
print(arr1, arr1.ndim)
print(arr2, arr2.ndim)

[[ 6.   1. ]
 [-5.2  3. ]
 [ 7.   0. ]] 2
[ 6.   1.  -5.2  3.   7.   0. ] 1


In [38]:
print(np.zeros((2, 3, 2)))

print(np.empty((3, 2, 1)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[ 1.5]
  [ 3. ]]

 [[-1. ]
  [ 0. ]]

 [[-3. ]
  [ 6.5]]]


arange는 파이썬의 range 함수의 배열 버전이다.

In [40]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])